"""Add datetime field

Revision ID: a8de44d1eb34
Revises: d12ce7d2d8b2
Create Date: 2024-01-31 09:47:41.025115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8de44d1eb34'
down_revision: Union[str, None] = 'd12ce7d2d8b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'created_at')
    # ### end Alembic commands ###
