"""Init

Revision ID: d12ce7d2d8b2
Revises: 
Create Date: 2024-01-30 17:59:07.764619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12ce7d2d8b2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('food_quality', sa.String(), nullable=True),
    sa.Column('food_quality_rate', sa.Integer(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('service_rate', sa.Integer(), nullable=True),
    sa.Column('ambiance', sa.String(), nullable=True),
    sa.Column('ambiance_rate', sa.Integer(), nullable=True),
    sa.Column('menu', sa.String(), nullable=True),
    sa.Column('menu_rate', sa.Integer(), nullable=True),
    sa.Column('cleanliness', sa.String(), nullable=True),
    sa.Column('cleanliness_rate', sa.Integer(), nullable=True),
    sa.Column('report', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    # ### end Alembic commands ###
